### ISSUE TITLE
dFRI recursive circuit components

### ISSUE THREAD

**Issue by Valeh2012** [NilFoundation/crypto3#327]
### TODO
- [ ]  Prepare input data
    - [ ]  Implement lpc proof batch generator
    - [ ]  Serialize all necessary data in JSON format
- [ ]  Get code that may be reused from placeholder_verifier component to dFRI component
    - [ ]  Work with transcript
    - [ ]  Initial merkle proof checks
    - [ ]  Round proofs merkle checks (except first round)
    - [ ]  Colinear checks
    - [ ]  Final polynomial checks
- [ ]  Implement linearity check component
- [ ]  Switch on first round merkle proof check
