### ISSUE TITLE
Stable zkLLVM C++ SDK

### ISSUE THREAD

**Issue by nkaskov** [NilFoundation/crypto3#53]
For the sake of our dev community extension, we need to prepare the SDK in a form, which everyone can use without crying.

That includes three main task types:

- CI and Unit-tests
- Documentation and manuals
- Understendable interfaces for common-used algorithms.

Circuit-specific algorithms implementations might not be very efficient, since this will be the goal for the future.

At this step, we only add tests for the most used and commonly updated modules.

- [ ] https://github.com/NilFoundation/crypto3-algebra/issues/103
- [ ] containers Unit-tests
- [ ] https://github.com/NilFoundation/crypto3-hash/issues/115
- [ ] algebra-marshalling Unit-tests
- [ ] core-marshalling Unit-tests
- [ ] multiprecision-marshalling Unit-tests
- [ ] zk-marshalling Unit-tests
- [ ] https://github.com/NilFoundation/crypto3-math/issues/43
- [ ] https://github.com/NilFoundation/crypto3-zk/issues/149
- [ ] https://github.com/NilFoundation/zkLLVM/issues/289
